import { ReactNode, useContext, useMemo } from 'react'
import { useRouter } from 'next/router';
import Head from 'next/head'
import { GlobalStateContext } from '@/context';

interface LayoutProps {
  children: ReactNode;
}

export default function Layout({ children }: LayoutProps): JSX.Element {
  const { name } = useContext(GlobalStateContext);
  const router = useRouter();

  const isHome = useMemo(() => router.pathname === '/', [router.pathname]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex gap-5">
          {!isHome && (
            <div onClick={() => router.back()} className="cursor-pointer">
              {`<`} Go Back
            </div>
          )}
          <span className="ml-2">
            The SpaceX app - {name}
          </span>
        </div>

        <div className="m-5">
          {children}
        </div>
      </main>
    </>
  );
}